name: Dev Freshness Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  check-branch-freshness:
    uses: Impaya/settings-and-wokflows/.github/workflows/reusable-branch-freshness-check.yml@main
    with:
      main_branch: "dev"
      has_update_script: "0"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
